'use strict';

var _ = require('lodash');
var Polyglot = require('node-polyglot');

module.exports.init = function(lang) {
  // Magic goes here: this file does not exist in the file system,
  // but will be generated by webpack (see webpack.config.js)
  var translations = require('./translations');
  var localeParts = lang ? lang.split('-') : [];
  var strings;
  if (localeParts.length > 1) {
    strings = _.extend({}, translations.en, translations[localeParts[0]],
      translations[lang]);
  } else {
    strings = _.extend({}, translations.en, translations[lang]);
  }
  var polyglot = new Polyglot();
  polyglot.extend(strings);
  return polyglot.t.bind(polyglot);
};

